wandb_version: 1

policy:
  desc: null
  value: MlpPolicy
learning_rate:
  desc: null
  value: 0.0003
buffer_size:
  desc: null
  value: 1000000
batch_size:
  desc: null
  value: 256
gamma:
  desc: null
  value: 0.99
tau:
  desc: null
  value: 0.005
total_timesteps:
  desc: null
  value: 5000000
_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.17.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1721156532
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 41
      - 53
      - 55
      3:
      - 16
      - 23
      - 35
      4: 3.8.10
      5: 0.17.4
      8:
      - 5
      13: linux-x86_64
