settings:
  mode: retraining # training, retraining, inference
  task: follow_lane_carla # follow_line_gazebo, follow_lane_gazebo, autoparking_gazebo
  algorithm: ddpg # qlearn, dqn, ddpg, ppo
  simulator: carla # openai, carla, gazebo, sumo
  environment_set: carla_environments # gazebo_environments, carla_environments
  env: follow_lane # Town01, simple, nurburgring, montreal, curves, simple_laser, manual, autoparking
  agent: auto_carla # auto_carla, autoparkingRL, auto_carla, mountain_car, robot_mesh, cartpole, turtlebot
  actions: continuous # slow, fast
  states: sp5 #image, sp1 (simplified perception with 1 point), sp3 (simplified perception with 3 points), spn (simplified perception with n points)
  rewards: followlane_center # followline_center, followline_center_v_w_linear
  framework: baselines # TensorFlow, Pytorch
  total_episodes: 5000000
  training_time: 72
  models_dir: "./checkpoints"
  recorder_carla_dir: "./recorders"
  logs_dir: "./logs"
  metrics_dir: "./metrics"
  debug_stats: false
  show_monitoring: false
  steps_to_decrease: 10000
  decrease_substraction: 0.003
  decrease_min: 0.003
  entropy_factor: 0
  reward_params:
    function: pow
    punish_zig_zag_value: 1
    punish_ineffective_vel: 1
    beta_1: 0.1 #ojooo sube estooo

ros:
  ros_master_uri: "11311"
  gazebo_master_uri: "11345"

retraining:
  ddpg:
    retrain_ddpg_tf_model_name: /home/ruben/Desktop/RL-Studio/rl_studio/checkpoints/follow_lane_carla_ddpg_auto_carla_baselines/20240924-163154/model_40000_steps.zip
inference:
  ddpg:
    retrain_ddpg_tf_model_name: /whatever

algorithm:
  ddpg:
    gamma: 0.9
    tau: 0.005
    std_dev: 0.05
    model_name: DDPG_Actor_conv2d32x64_Critic_conv2d32x64
    replay_memory_size: 10_000
    memory_fraction: 0.20
    critic_lr: 0.0003
    actor_lr: 0.0002
    buffer_capacity: 100_000
    batch_size: 120

agents:
  auto_carla:
    camera_params:
      width: 640
      height: 480
      center_image: 320
      raw_image: False
      image_resizing: 100
      new_image_size: 32
      num_regions: 16
      lower_limit: 220

states:
  image:
    0: [3]
  sp1:
    0: [40] #TODO
  sp3:
    0: [10, 50, 150]
  sp5:
    0: [280, 340, 380, 420, 460]
  sp10:
    0: [270, 280, 290, 300, 310, 330, 370, 400, 430, 460]
  spn:
    0: [10]

actions:
  continuous:
    v: [0, 1]
    w: [-0.5, 0.5]
    b: [0, 1]


rewards:
  followlane_center:

carla_environments:
  follow_lane:
    env_name: CarlaEnv-v0
    town: Town04 #Town01, Town02, Town03, Town04, Town05, Town10HD
    # Town01_Opt, Town02_Opt, Town03_Opt, Town04_Opt, Town05_Opt, Town10HD_Opt
    car: model1
    weather: ClearNoon #dynamic, argparse
    traffic_pedestrians: False
    city_lights: False
    car_lights: False
    estimated_steps: 5000
    save_episodes: 5 # not used in this carla ppo
    save_every_step: 100 # not used in this carla ppo
    goal_pose:
    init_pose:
    filter: vehicle.*
    generation: "2"
    rolename: "hero" #name
    gamma: 2.2 #for camera
    sync: True #syncronous mode or async
    detection_mode: lane_detector_v2
    fixed_delta_seconds: 0.1
    async_forced_delta_seconds: 0
    reset_threshold: 0.35
    alternate_pose: True
    spawn_points: [
      [ -475.906342, 352.208710, 1.007515, 0.051254, 55.662395, 0.072115 ],
      [12.593741, 156.040146, 1.008111, 0.118347, -90.375160, 20.1006703],
      [384.381470, -47.060329, 1.007339, 0.031453, 90.310402, 0.008101],
      [199.221252, -367.893829, 0.809260, 0.248796, 0.152361, -0.002625],
      [235.603699, 12.395636, 5.228042, 3.577455, 0.124573, -0.008118],
      [389.585938, -176.352158, 0.807793, 0.082516, 270.889893, 0.078263]
    ]
    waypoints_meters: 5 #distance between waypoints in meters
    waypoints_init: 6912 # {6912} 1471 6927 899 6294    waypoints_target: 959 #961
    waypoints_target: 959 #961
    waypoints_lane_id: -1
    waypoints_road_id: 8

carla:
  carla_server: localhost
  carla_client: 4001
  manager_port: 8022
